name: dgg
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.2+6

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  
  #state management
  stacked: ^1.7.6
  #navigation
  auto_route: ^0.6.9
  stacked_services: ^0.7.3
  #inversion of control
  get_it: ^5.0.1
  injectable: ^1.0.5

  #TODO still need to do iOS setup
  #firebase
  firebase_core: ^0.5.2+1
  firebase_remote_config: ^0.4.2
  firebase_crashlytics: "^0.2.4"
  firebase_analytics: "^6.3.0"

  #oauth
  uni_links: ^0.4.0
  crypto: ^2.1.5

  #other
  shared_preferences: ^0.5.10
  http: ^0.12.2
  webview_flutter: ^1.0.1
  webview_cookie_manager: ^1.0.3
  web_socket_channel: ^1.1.0
  url_launcher: ^5.7.0
  image: ^2.1.18
  flutter_staggered_animations: ^0.1.2
  settings_ui: ^0.5.0
  wakelock: ^0.2.1+1
  introduction_screen: ^1.0.9
  stacked_themes: ^0.2.2+2
  adaptive_dialog: ^0.9.3
  percent_indicator: ^2.1.9
  extended_nested_scroll_view: ^2.0.1
  youtube_player_iframe: ^1.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.0.6

  flutter_launcher_icons: ^0.8.1

#TODO need to make iOS icons later
#To run:
#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: false
  ios: false
  image_path_android: "assets/images/dgg_icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/dgg_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/dgg_icon.png
    - assets/images/dgg_logo.png
    - assets/images/login_key.png
